FROM openjdk:21-slim-buster

ARG POSTGRES_HOST
ENV POSTGRES_HOST $POSTGRES_HOST
ARG POSTGRES_PORT
ENV POSTGRES_PORT $POSTGRES_PORT
ARG POSTGRES_DB
ENV POSTGRES_DB $POSTGRES_DB
ARG POSTGRES_USER
ENV POSTGRES_USER $POSTGRES_USER
ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD

WORKDIR /dist
USER 1000
VOLUME /tmp
COPY /sandbox/target/sandbox-0.0.1-SNAPSHOT.jar /dist/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar", "app.jar"]